### PR TITLE
Upgrade paramiko version to 2.10.0

### PR DESCRIPTION
**Pull request by lbradstreet**
This fixes authentication issues when using pem files with ubuntu 22 (LTS).

### CODE REVIEW

**Comment by imcdo** [comment]
Hi @lbradstreet can you change the merge target to 0.8.x (or even 0.7.x if this version is supported by python2)

**Review by imcdo — APPROVED** [review]
lgtm

**Comment by stan-confluent** [comment]
@lbradstreet  I have a separate PR that introduces requirements.txt, will merge that one first and then update this one

**Comment by stan-confluent** [comment]
I'm closing this one as a duplicate

**Pull request closed without merging**
