### PR TITLE
Add HTML reporter

### PR DESCRIPTION
**Pull request by Ishiihara**
@ewencp @granders This PR adds the HTML reporter to ducktape. Note that the running time and log file are currently mocked and will be modified once log patch in committed.

### CODE REVIEW

**Comment by ewencp** [comment]
LGTM once the changes you mentioned are made. One question I have is whether we plan to keep both the HTMLReporter and SimpleFileReporter? If we do, HTMLReporter will probably always be dependent on the SimpleFileReporter since the html will link to files generated by the SimpleFileReporter. Not necessarily a problem, but it does mean that an option that controls the type of reporter would be more complicated to implement (needs to know implementation details of the classes rather than just know how to instantiate and use one of them specified by name).

**Comment by granders** [comment]
Thanks @Ishiihara!
@ewencp Right now as far as I can tell, these two reports are generating independent views of the same data. As I understand it the links will point to the log files generated while the tests run. Log files are generated independently, and are written regardless of which reporter is used.

Perhaps 'SummaryReporter' would be a more accurate name for the class.

**Comment by granders** [comment]
@Ishiihara @ewencp 
Paths to the individual per-test log files are only available in my current pull request (log-output branch) - perhaps it makes sense to just merge this and then link things together once I merge in log-output?

**Comment by ewencp** [comment]
Ah right, that makes sense since the logger is just setup to pipe to a file.

I think this setup will work for now, but it could be a bit brittle -- the report will rely on details implemented elsewhere with no way to know if they change. Would it make sense to file an issue to later address this by to better integrating these two? I'm thinking that the right solution might be to let the reporter control all the output, which in this case would mean that when loggers are setup, that process is actually delegated to the Reporter so it can control what happens with it (e.g. gets put on disk on its own, gets embedded in an HTML report, etc.). On the other hand, this could make the Reporter have to interact with a bunch of stuff since the location of service files that are downloaded from worker nodes would also logically be under the Reporter's control since it also needs to link to them.

**Comment by ewencp** [comment]
@granders Up to you how these get merged and linked up since right now it's not really a problem to have not-quite-complete features checked in.

**Comment by granders** [comment]
@ewencp Hm I think I see your point - you seem to be envisioning the reporter as something which intercepts and routes all messages, whereas I had originally conceived of it as strictly a 'summarize results' mechanism, with a clear enough interface on the TestResult class to make it simple to do so.

 Yeah maybe file an issue - it's certainly worth discussing the tradeoffs.

**Pull request merged**
