### PR TITLE
Add optional clean parameter to Service.start.

### LINKED ISSUE #255: Add optional `clean` parameter to `Service.start`
Sometimes during tests it is required to restart service with same persistence without cleaning node.
I suggests to add optional `clean` parameter to `Service.start` with defaults to `True`

Fixed in #254

### PR DESCRIPTION
**Pull request by ivandasch**
Fix #255

### CODE REVIEW

**Comment by nizhikov** [comment]
Looks like a nice addition for me.

@ewencp Can you, please, take a look?

**Comment by stan-confluent** [comment]
Thanks @ivandasch , this is a good addition indeed. Can you please add a test as well? I know the code is super simple right now, but good to have it tested for when someone inevitably changes something in that class in the future.

**Comment by ivandasch** [comment]
@stan-confluent I suppose, systest is needed here, isn't it?

**Comment by stan-confluent** [comment]
@ivandasch thanks! honestly, a simple unit test will do, to ensure clean is called for each node; exception doesn't stop cleaning other nodes and clean is not called when parameter is passed

**Comment by ivandasch** [comment]
@stan-confluent Done, i've added some tests + fix some codestyle issues (minor)

**Comment by ivandasch** [comment]
@stan-confluent May I ask you a question about new release with this and previous my PR's? I'd like to ask you because custom fork of ducktape with my patches is used in Apache Ignite ducktape tests and we are going to merge them in master. It would be nice if we could use release version of ducktape from pip.

**Review by stan-confluent — APPROVED** [review]

**Comment by stan-confluent** [comment]
@ivandasch Thanks for adding the test!
As for the release, yeah, definitely! Ducktape did not get enough attention lately due to various factors, but that should not be the case going forward, hopefully.
We don't have automated release pipeline yet, but I'll be releasing from 0.8.x branch as needed, so please target that branch in your PRs. I'll push 0.8.2 to pypi when this PR is in (in other words, soon)
Thanks for helping to make ducktape better :)

**Comment by stan-confluent** [comment]
@ivandasch I've just published ducktape 0.8.2 into pypi, this should include all your recently merged PRs as well as our PR for adding test parameter support #266

**Comment by ivandasch** [comment]
@stan-confluent Great news, thank you very much! We are going to migrate to this version ASAP.

**Comment by ivandasch** [comment]
@stan-confluent  Unfortunatelly, smth went wrong
```
(test-ducktape-0.8.2) ➜  tests git:(additional-unittest-merge-jvm) ✗ pip install ducktape==0.8.2
Collecting ducktape==0.8.2
  Could not find a version that satisfies the requirement ducktape==0.8.2 (from versions: 0.1, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.7.10, 0.7.11, 0.8.0, 0.8.1)
No matching distribution found for ducktape==0.8.2
```
But new version is announced on [pypi](https://pypi.org/project/ducktape/0.8.2/)

**Comment by ivandasch** [comment]
@stan-confluent Oops, found that required version of python is >= 3.7  But I tested master on 3.6 without any problem
Issue #269 created.

**Pull request merged**
